repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
    -   id: black
        language_version: python3.8
        args: ["--line-length=120"]
# -   repo: https://github.com/pycqa/flake8
#     rev: 7.1.1
#     hooks:
#     -   id: flake8
 